import type { Metadata } from 'next'
import 'bootstrap/dist/css/bootstrap.css'
import ImportBsJS from "./importBsJS";
import { Varela_Round, Oswald } from 'next/font/google'
import './globals.css'
import Header from './Header'
import Footer from './Footer'
import Sidebar from './Sidebar';

export const varelaRound = Varela_Round({
  subsets: ['latin'], display: 'swap',
  weight: ['400',],
  variable: '--font-varelaRound',
});

export const oswald = Oswald({
  subsets: ['latin'], display: 'swap',
  weight: ['400', '500', '600', '700'],
  variable: '--font-oswald',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ImportBsJS />
      <body className={`${varelaRound.variable} ${oswald.variable}`}>
        <Header />
        <main className="main-container d-flex">
          <Sidebar />
          <div className="main-body d-flex flex-column overflow-y-auto">
            {children}
            <Footer />
          </div>
        </main>
      </body>
    </html>
  )
}
